export const MUSIC_STYLES = [
  { value: "techno", label: "Techno" },
  { value: "house", label: "House" },
  { value: "trance", label: "Trance" },
  { value: "hardcore", label: "Hardcore/Hardstyle" },
  { value: "dnb", label: "Drum & Bass" },
  { value: "dubstep", label: "Dubstep" },
  { value: "trap", label: "Trap" },
  { value: "hiphop", label: "Hip-Hop" },
  { value: "rap", label: "Rap" },
  { value: "rnb", label: "R&B" },
  { value: "pop", label: "Pop" },
  { value: "rock", label: "Rock" },
  { value: "metal", label: "Metal" },
  { value: "reggae", label: "Reggae" },
  { value: "funk", label: "Funk" },
  { value: "disco", label: "Disco" },
  { value: "jazz", label: "Jazz" },
  { value: "classical", label: "Classique" },
  { value: "ambient", label: "Ambient" },
  { value: "world", label: "Musiques du monde" },
  { value: "other", label: "Autre" },
]; 