export const MUSIC_STYLES = [
  { value: "french_chanson", label: "Variété / Chanson française" },
  { value: "pop_folk", label: "Pop / Folk" },
  { value: "rock_punk", label: "Rock / Punk" },
  { value: "rap_hiphop", label: "Rap / Hip-Hop" },
  { value: "rnb_soul", label: "R&B / Soul" },
  { value: "funk_disco", label: "Funk / Disco" },
  { value: "electronic", label: "Musiques électroniques" },
  { value: "jazz_blues", label: "Jazz / Blues" },
  { value: "classical", label: "Musique classique" },
  { value: "metal_hardrock", label: "Metal / Hard Rock" },
  { value: "latin", label: "Musique latine" },
  { value: "reggae_dub", label: "Reggae / Dub" },
  { value: "dancehall_zouk", label: "Dancehall / Zouk" },
  { value: "kpop", label: "K-Pop" },
  { value: "other", label: "Autre" },
]; 